---
# Specify if more messages should be displayed during the executions.
debug: false

# The domain name of the HomeLab.
domain: "aprendendo.com.br"

# The id that will be used to retrieve the truenas's root password saved in the MacOSX Keychain. It will be the same for all hosts.
root_password_id: "truenas-root-password"

# The id that will be used to retrieve the truenas's SMTP password saved in the MacOSX Keychain. It will be the same for all hosts.
smtp_password_id: "truenas-smtp-password"

# The id that will be used to retrieve the root's API Key saved in the MacOSX Keychain. It will be used to make web requests.
api_key_id: "truenas-api-key"

# The password of the root user used in TrueNAS.
api_key: "{{ lookup('pipe', 'security find-generic-password -a $USER -s {{ api_key_id }} -w') }}"

# The protocol that will be used. Can be HTTP or HTTPS.
http_protocol: "https://"

# The path of the api's.
api_url: "{{ base_url }}/api/v2.0"

# The path of the tasks in the common role.
role_common_task: "roles/common/tasks"

# The path of the known_hosts add task.
role_common_task_known_hosts_add: "{{ role_common_task }}/known_hosts/add.yml"

# The path of the packages folder.
role_common_task_packages: "{{ role_common_task }}/packages"

# The path of the packages pip task.
role_common_task_packages_pip: "{{ role_common_task_packages }}/pip.yml"

# The path of the packages sshpass task.
role_common_task_packages_sshpass: "{{ role_common_task_packages }}/sshpass.yml"

# The path of the passwords folder.
role_common_task_passwords: "{{ role_common_task }}/passwords"

# The path of the password add task.
role_common_task_password_add: "{{ role_common_task_passwords }}/add.yml"

# The path of the password get task.
role_common_task_password_get: "{{ role_common_task_passwords }}/get.j2"

# The path of the shared folder.
role_common_task_shared: "{{ role_common_task }}/shared"

# The path of the shared compare dict vs json task.
role_common_task_shared_compare_dict_json: "{{ role_common_task_shared }}/compare-dict-json.yml"

# The path of the shared delete settings task.
role_common_task_shared_delete_settings: "{{ role_common_task_shared }}/delete-settings.yml"

# The path of the shared generic get compare update settings task.
role_common_task_shared_get_compare_update_settings: "{{ role_common_task_shared }}/get-compare-update-settings.yml"

# The path of the shared get current settings task.
role_common_task_shared_get_current_settings: "{{ role_common_task_shared }}/get-current-settings.yml"

# The path of the shared get desired settings task.
role_common_task_shared_get_desired_settings: "{{ role_common_task_shared }}/get-desired-settings.yml"

# The path of the shared update settings task.
role_common_task_shared_update_settings: "{{ role_common_task_shared }}/update-settings.yml"

# The path of the uri certificate folder.
role_common_task_uri: "{{ role_common_task }}/uri"

# The path of the uri network folder.
role_common_task_uri_network: "{{ role_common_task_uri }}/network"

# The path of the uri network configuration folder.
role_common_task_uri_network_configuration: "{{ role_common_task_uri_network }}/configuration"

# The path of the uri network configuration get task.
role_common_task_uri_network_configuration_get: "{{ role_common_task_uri_network_configuration }}/get.yml"

# The path of the uri network configuration update task.
role_common_task_uri_network_configuration_update: "{{ role_common_task_uri_network_configuration }}/update.yml"

# The path of the uri service folder.
role_common_task_uri_service: "{{ role_common_task_uri }}/service"

# The path of the uri service iscsi folder.
role_common_task_uri_service_iscsi: "{{ role_common_task_uri_service }}/iscsi"

# The path of the uri service iscsi get task.
role_common_task_uri_service_iscsi_get: "{{ role_common_task_uri_service_iscsi }}/get.yml"

# The path of the uri service iscsi update task.
role_common_task_uri_service_iscsi_update: "{{ role_common_task_uri_service_iscsi }}/update.yml"

# The path of the uri service nfs folder.
role_common_task_uri_service_nfs: "{{ role_common_task_uri_service }}/nfs"

# The path of the uri service nfs get task.
role_common_task_uri_service_nfs_get: "{{ role_common_task_uri_service_nfs }}/get.yml"

# The path of the uri service nfs update task.
role_common_task_uri_service_nfs_update: "{{ role_common_task_uri_service_nfs }}/update.yml"

# The path of the uri service smart folder.
role_common_task_uri_service_smart: "{{ role_common_task_uri_service }}/smart"

# The path of the uri service smart get task.
role_common_task_uri_service_smart_get: "{{ role_common_task_uri_service_smart }}/get.yml"

# The path of the uri service smart update task.
role_common_task_uri_service_smart_update: "{{ role_common_task_uri_service_smart }}/update.yml"

# The path of the uri service ssh folder.
role_common_task_uri_service_ssh: "{{ role_common_task_uri_service }}/ssh"

# The path of the uri service ssh get task.
role_common_task_uri_service_ssh_get: "{{ role_common_task_uri_service_ssh }}/get.yml"

# The path of the uri service ssh update task.
role_common_task_uri_service_ssh_update: "{{ role_common_task_uri_service_ssh }}/update.yml"

# The path of the service enable task.
role_common_task_uri_service_enable: "{{ role_common_task_uri_service }}/enable.yml"

# The path of the service get task.
role_common_task_uri_service_get: "{{ role_common_task_uri_service }}/get.yml"

# The path of the service start task.
role_common_task_uri_service_start: "{{ role_common_task_uri_service }}/start.yml"

# The path of the uri storage folder.
role_common_task_uri_storage: "{{ role_common_task_uri }}/storage"

# The path of the uri storage pool folder.
role_common_task_uri_storage_pool: "{{ role_common_task_uri_storage }}/pool"

# The path of the uri storage pool create task.
role_common_task_uri_storage_pool_create: "{{ role_common_task_uri_storage_pool }}/create.yml"

# The path of the uri storage pool get task.
role_common_task_uri_storage_pool_get: "{{ role_common_task_uri_storage_pool }}/get.yml"

# The path of the uri storage pool update task.
role_common_task_uri_storage_pool_update: "{{ role_common_task_uri_storage_pool }}/update.yml"

# The path of the uri system folder.
role_common_task_uri_system: "{{ role_common_task_uri }}/system"

# The path of the uri system advanced folder.
role_common_task_uri_system_advanced: "{{ role_common_task_uri_system }}/advanced"

# The path of the uri system advanced get settings task.
role_common_task_uri_system_advanced_get: "{{ role_common_task_uri_system_advanced }}/get.yml"

# The path of the uri system advanced update task.
role_common_task_uri_system_advanced_update: "{{ role_common_task_uri_system_advanced }}/update.yml"

# The path of the uri certificate folder.
role_common_task_uri_system_certificate: "{{ role_common_task_uri_system }}/certificate"

# The path of the uri certificate create task.
role_common_task_uri_system_certificate_create: "{{ role_common_task_uri_system_certificate }}/create.yml"

# The path of the uri certificate get task.
role_common_task_uri_system_certificate_get: "{{ role_common_task_uri_system_certificate }}/get.yml"

# The path of the uri certificate update task.
role_common_task_uri_system_certificate_update: "{{ role_common_task_uri_system_certificate }}/update.yml"

# The path of the uri system general folder.
role_common_task_uri_system_general: "{{ role_common_task_uri_system }}/general"

# The path of the uri system general get settings task.
role_common_task_uri_system_general_get: "{{ role_common_task_uri_system_general }}/get.yml"

# The path of the uri system general update task.
role_common_task_uri_system_general_update: "{{ role_common_task_uri_system_general }}/update.yml"

# The path of the uri system general ui restart task.
role_common_task_uri_system_general_ui_restart: "{{ role_common_task_uri_system_general }}/ui-restart.yml"

# The path of the uri system mail folder.
role_common_task_uri_system_mail: "{{ role_common_task_uri_system }}/mail"

# The path of the uri system mail get task.
role_common_task_uri_system_mail_get: "{{ role_common_task_uri_system_mail }}/get.yml"

# The path of the uri system mail update task.
role_common_task_uri_system_mail_update: "{{ role_common_task_uri_system_mail }}/update.yml"

# The path of the uri system ntpserver folder.
role_common_task_uri_system_ntpserver: "{{ role_common_task_uri_system }}/ntpserver"

# The path of the uri system ntpserver create task.
role_common_task_uri_system_ntpserver_create: "{{ role_common_task_uri_system_ntpserver }}/create.yml"

# The path of the uri system ntpserver delete task.
role_common_task_uri_system_ntpserver_delete: "{{ role_common_task_uri_system_ntpserver }}/delete.yml"

# The path of the uri system ntpserver get task.
role_common_task_uri_system_ntpserver_get: "{{ role_common_task_uri_system_ntpserver }}/get.yml"

# The path of the uri system ntpserver update task.
role_common_task_uri_system_ntpserver_update: "{{ role_common_task_uri_system_ntpserver }}/update.yml"

# The path of the uri system state folder.
role_common_task_uri_system_state: "{{ role_common_task_uri_system }}/state"

# The path of the uri system state get task.
role_common_task_uri_system_state_get: "{{ role_common_task_uri_system_state }}/get.yml"

# The path of the web folder.
role_common_task_web: "{{ role_common_task }}/web"

# The path of the web delete task.
role_common_task_web_delete: "{{ role_common_task_web }}/delete.yml"

# The path of the web get task.
role_common_task_web_get: "{{ role_common_task_web }}/get.yml"

# The path of the web post task.
role_common_task_web_post: "{{ role_common_task_web }}/post.yml"

# The path of the web put task.
role_common_task_web_put: "{{ role_common_task_web }}/put.yml"

# The path of the web request task.
role_common_task_web_request: "{{ role_common_task_web }}/request.yml"

# The url of the network page
url_network: "{{ api_url }}/network"

# The url of the network configuration page
url_network_configuration: "{{ url_network }}/configuration"

# The url of the service page
url_service: "{{ api_url }}/service"

# The url of the service iscsi page
url_service_iscsi: "{{ api_url }}/iscsi"

# The url of the service iscsi page
url_service_iscsi_global: "{{ url_service_iscsi }}/global"

# The url of the service nfs page
url_service_nfs: "{{ api_url }}/nfs"

# The url of the service smart page
url_service_smart: "{{ api_url }}/smart"

# The url of the service ssh page
url_service_ssh: "{{ api_url }}/ssh"

# The url of the service enable page
url_service_enable: "{{ url_service }}/id"

# The url of the service start page
url_service_start: "{{ url_service }}/start"

# The url of the sharing page
url_sharing: "{{ api_url }}/sharing"

# The url of the sharing nfs page
url_sharing_nfs: "{{ url_sharing }}/nfs"

# The url of the sharing nfs set page
url_sharing_nfs_update: "{{ url_sharing_nfs }}/id"

# The url of the storage pool page
url_storage_pool: "{{ api_url }}/pool"

# The url of the storage set pool page
url_storage_pool_by_id: "{{ url_storage_pool }}/id"

# The url of the system page
url_system: "{{ api_url }}/system"

# The url of the system advanced page
url_system_advanced: "{{ url_system }}/advanced"

# The url of the system general page
url_system_general: "{{ url_system }}/general"

# The url of the system general ui_restart page
url_system_general_ui_restart: "{{ url_system_general }}/ui_restart"

# The url of the system mail page
url_system_mail: "{{ api_url }}/mail"

# The url of the system ntpserver page
url_system_ntpserver: "{{ url_system }}/ntpserver"

# The url of the system ntpserver set page
url_system_ntpserver_by_id: "{{ url_system_ntpserver }}/id"

# The url of the system state page
url_system_state: "{{ url_system }}/state"

# The url of the certificate page
url_certificate: "{{ api_url }}/certificate"
