---
# Specify if more messages should be displayed during the executions.
debug: false

# The domain name of the HomeLab.
domain: "homelab"

# The id that will be used to retrieve the truenas's root password saved in the MacOSX Keychain. It will be the same for all hosts.
root_password_id: "truenas-root-password"

# The id that will be used to retrieve the truenas's SMTP password saved in the MacOSX Keychain. It will be the same for all hosts.
smtp_password_id: "truenas-smtp-password"

# The id that will be used to retrieve the root's API Key saved in the MacOSX Keychain. It will be used to make web requests.
api_key_id: "truenas-api-key"

# The password of the root user used in TrueNAS.
api_key: "{{ lookup('pipe', 'security find-generic-password -a $USER -s {{ api_key_id }} -w') }}"

# The protocol that will be used. Can be HTTP or HTTPS.
http_protocol: "https://"

# The path of the api's.
api_url: "{{ base_url }}/api/v2.0"

# The url of the network page
url_network: "{{ api_url }}/network"

# The url of the network configuration page
url_network_configuration: "{{ url_network }}/configuration"

# The url of the service page
url_service: "{{ api_url }}/service"

# The url of the service iscsi page
url_service_iscsi: "{{ api_url }}/iscsi"

# The url of the service iscsi page
url_service_iscsi_global: "{{ url_service_iscsi }}/global"

# The url of the service nfs page
url_service_nfs: "{{ api_url }}/nfs"

# The url of the service smart page
url_service_smart: "{{ api_url }}/smart"

# The url of the service ssh page
url_service_ssh: "{{ api_url }}/ssh"

# The url of the service enable page
url_service_enable: "{{ url_service }}/id"

# The url of the service start page
url_service_start: "{{ url_service }}/start"

# The url of the sharing page
url_sharing: "{{ api_url }}/sharing"

# The url of the sharing nfs page
url_sharing_nfs: "{{ url_sharing }}/nfs"

# The url of the sharing nfs set page
url_sharing_nfs_update: "{{ url_sharing_nfs }}/id"

# The url of the storage pool page
url_storage_pool: "{{ api_url }}/pool"

# The url of the storage set pool page
url_storage_pool_by_id: "{{ url_storage_pool }}/id"

# The url of the system page
url_system: "{{ api_url }}/system"

# The url of the system advanced page
url_system_advanced: "{{ url_system }}/advanced"

# The url of the system general page
url_system_general: "{{ url_system }}/general"

# The url of the system general ui_restart page
url_system_general_ui_restart: "{{ url_system_general }}/ui_restart"

# The url of the system mail page
url_system_mail: "{{ api_url }}/mail"

# The url of the system ntpserver page
url_system_ntpserver: "{{ url_system }}/ntpserver"

# The url of the system ntpserver set page
url_system_ntpserver_by_id: "{{ url_system_ntpserver }}/id"

# The url of the system state page
url_system_state: "{{ url_system }}/state"

# The url of the certificate page
url_certificate: "{{ api_url }}/certificate"

# The path of the tasks in the common role.
role_common_task: "roles/common/tasks"

# The path of the passwords folder.
role_common_task_passwords: "{{ role_common_task }}/passwords"

# The path of the shared folder.
role_common_task_shared: "{{ role_common_task }}/shared"

# The path of the shared compare dict vs json task.
role_common_task_shared_compare_dict_json: "{{ role_common_task_shared }}/compare-dict-json.yml"

# The path of the shared delete settings task.
role_common_task_shared_delete_settings: "{{ role_common_task_shared }}/delete-settings.yml"

# The path of the shared generic get compare update settings task.
role_common_task_shared_get_compare_update_settings: "{{ role_common_task_shared }}/get-compare-update-settings.yml"

# The path of the shared get current settings task.
role_common_task_shared_get_current_settings: "{{ role_common_task_shared }}/get-current-settings.yml"

# The path of the shared get desired settings task.
role_common_task_shared_get_desired_settings: "{{ role_common_task_shared }}/get-desired-settings.yml"

# The path of the shared update settings task.
role_common_task_shared_update_settings: "{{ role_common_task_shared }}/update-settings.yml"

# The path of the uri certificate folder.
role_common_task_uri: "{{ role_common_task }}/uri"

# The path of the uri storage folder.
role_common_task_uri_storage: "{{ role_common_task_uri }}/storage"

# The path of the web folder.
role_common_task_web: "{{ role_common_task }}/web"

# The path of the web delete task.
role_common_task_web_delete: "{{ role_common_task_web }}/delete.yml"

# The path of the web get task.
role_common_task_web_get: "{{ role_common_task_web }}/get.yml"

# The path of the web post task.
role_common_task_web_post: "{{ role_common_task_web }}/post.yml"

# The path of the web put task.
role_common_task_web_put: "{{ role_common_task_web }}/put.yml"

# The path of the web request task.
role_common_task_web_request: "{{ role_common_task_web }}/request.yml"
