---
- name: Adding the "{{ root_password_id }}" password into the Secret Manager
  include_tasks: "{{ role_common_task_password_add }}"
  vars:
    password_id : "{{ root_password_id }}"
    password: "{{ root_password }}"
  when: root_password | length > 0
  no_log: True

- name: Adding the "{{ smtp_password_id }}" password into the Secret Manager
  include_tasks: "{{ role_common_task_password_add }}"
  vars:
    password_id : "{{ smtp_password_id }}"
    password: "{{ smtp_password }}"
  when: smtp_password | length > 0
  no_log: True
