---
- name: Setting up the control machine to run Ansible scripts
  hosts: "ControlMachine"
  vars_prompt:
    - name: "root_password"
      prompt: "What is the TrueNAS's root password? (empty to skip) "
      private: True
    - name: "smtp_password"
      prompt: "What is the TrueNAS's SMTP password? (empty to skip) "
      private: True
      
  roles:
    - 01-control-machine
