---
- name: Setting up the system's preferences
  hosts: "ControlMachine"
  
  tasks:
    - name: Calling the role that contains all the necessary tasks
      include_role:
        name: 02-system
      loop: "{{ groups['TrueNAS'] }}"
      loop_control:
          loop_var: host