---
- name: Setting up the services that will be used by TrueNAS
  hosts: "ControlMachine"
  
  tasks:
    - name: Calling the role that contains all the necessary tasks
      include_role:
        name: 09-services
      loop: "{{ groups['TrueNAS'] }}"
