---
- name: Calling the generic playbook to verify if the current and desired network settings are different and if they are, update it
  include_tasks: "{{ role_common_task_shared_get_compare_update_settings }}"
  vars:
    service_display_name: "network"
    service_name: "configuration"
    task_get_settings: "{{ role_common_task_uri_network_configuration_get }}"
    task_update_settings: "{{ role_common_task_uri_network_configuration_update }}"
