---
- name: Reading the json file that contains the desired settings
  include_tasks: "{{ role_common_task_shared_get_desired_settings }}"
  vars:
    template_file: "mail/config.json"

- name: Getting the current mail settings
  include_tasks: "{{ role_common_task_shared_get_current_settings }}"
  vars:
    task_file: "{{ role_common_task_uri_system_mail_get }}"

- name: Comparing the desired and current settings
  include_tasks: "{{ role_common_task_shared_compare_dict_json }}"
  vars:
    dict: "{{ desired_settings }}"
    json: "{{ response.json }}"

- name: Setting the mail settings
  include_tasks: "{{ role_common_task_shared_update_settings }}"
  vars:
    task_file: "{{ role_common_task_uri_system_mail_update }}"
  when: different_settings | length > 0
