---
- name: Including the file that contains specific settings
  include_vars: "host_vars/{{ host }}.yml"

- name: Setting up the network global configuration
  import_tasks: "nfs/main.yml"
  vars:
    pool_name: "{{ item.pool_name }}"
    pool_type_raid: "{{ item.pool_type_raid }}"
    pool_disks: "{{ item.pool_disks }}"
  loop:
    - { 
        pool_name: "{{ pool_bronze_name }}", 
        pool_type_raid: "{{ pool_bronze_type_raid }}", 
        pool_disks: "{{ pool_bronze_disks }}" 
      }
  loop_control:
    label: "{{ item.pool_name}}"
