---
- name: Deleting the default TrueNAS NTP servers
  include_tasks: "delete.yml"

- name: Creating the Brazilian NTP servers settings
  include_tasks: "create.yml"
  vars:
    ntp_server: "{{ item }}"
  loop: "{{ ntp_servers }}"
