---
- name: Creating the dict that will contain the elements that are different (current vs desired)
  set_fact:
    different_elements: {}

- name: Comparing the desired and current settings
  set_fact:
    different_elements: "{{ (current != desired) | ternary(different_elements | combine ({ element.key : element.value }), different_elements) }}"
  vars:
    current: "{{ json['%s' | format(element.key)] | default() }}"
    desired: "{{ element.value }}"
  loop: "{{ dict | dict2items }}"
  loop_control:
    loop_var: "element"
    label: "{{ element.key }}"
