---
- name: Creating temporary variables to assign some default values
  set_fact:
    changed_when_temp: "{{ changed_when | default(false) }}"

- name: Making a request to the URL '{{ url }}' using the DELETE method
  include_tasks: "{{ role_common_task_web_request }}"
  vars:
    method: "DELETE"
    changed_when: "{{ changed_when_temp }}"
