---
- name: Making a request to the URL '{{ url }}' using the POST method
  include_tasks: "{{ role_common_task_web_request }}"
  vars:
    method: "POST"
    body_format: "{{ body_format | default('json') }}"
