---
- name: Printing the request body object
  debug:
    msg: "{{ body | default('') }}"
  when: debug | bool

- name: Making a web request
  delegate_to: "{{ delegate_to | default(omit) }}"
  uri:
    method: "{{ method }}"
    url: "{{ url }}"
    return_content: "{{ return_content | default(omit) }}"
    status_code: "{{ status_code | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    follow_redirects: "{{ follow_redirects | default(omit) }}"
    force: "{{ force | default(omit) }}"
    body_format: "{{ body_format | default(omit) }}"
    body: "{{ body | default(omit) }}"
    headers:
      Content-Type: "{{ Content_Type | default('application/json') }}"
      Authorization: "Bearer {{ api_key }}"
  register: "response"
  changed_when: (changed_when is defined) | ternary(changed_when, (status_code is defined) | ternary(response.status in (status_code | default([])), (response.status in [200])))
  until: "until | default(omit)"
  delay: "{{ delay | default(omit) }}"
  retries: "{{ retries | default(omit) }}"

- name: Printing the response object
  debug:
    var: "response"
  when: debug | bool