---
- name: Calling the generic playbook to verify if the current and desired SSH settings are different and if they are, update it
  include_tasks: "{{ role_common_task_shared_get_compare_update_settings }}"
  vars:
    task_get_settings: "{{ role_common_task_uri_service_ssh_get }}"
    task_update_settings: "{{ role_common_task_uri_service_ssh_update }}"
