---
- name: Installing and upgrading the pip package
  pip:
    name: "pip"
    state: "present"

- name: Installing all the required Python packages
  pip:
    name: "{{ item }}"
    state: "present"
  loop:
    - "passlib"
