---
- name: Reading the json file that contains the desired settings
  include_tasks: "{{ role_common_task_shared_get_desired_settings }}"
  vars:
    template_file: "general/config.json"

- name: Getting the current system general settings
  include_tasks: "{{ role_common_task_shared_get_current_settings }}"
  vars:
    task_file: "{{ role_common_task_uri_system_general_get }}"

- name: Comparing the desired and current settings
  include_tasks: "{{ role_common_task_shared_compare_dict_json }}"
  vars:
    dict: "{{ desired_settings }}"
    json: "{{ response.json }}"
  
- name: Setting the system general settings
  include_tasks: "{{ role_common_task_shared_set_settings }}"
  vars:
    task_file: "{{ role_common_task_uri_system_general_set }}"
  when: different_settings | length > 0
