---
- name: Calling the generic playbook to verify if the current and desired settings are different and if they are, update it
  include_tasks: "{{ role_common_task_shared_get_compare_update_settings }}"
  vars:
    service_display_name: "system general"
    service_name: "general"
    task_get_settings: "{{ role_common_task_uri_system_general_get }}"
    task_update_settings: "{{ role_common_task_uri_system_general_update }}"
