---
- name: Including the file that contains specific settings
  include_vars: "{{ item }}.yml"
  
- name: Getting the list of services 
  include_tasks: "{{ role_common_task_web_get }}"
  vars:
    url: "{{ api_url }}/service"

- name: Getting the current settings of the iSCSI service
  set_fact:
    json: "{{ response.json | json_query('[?service==`iscsitarget`]') | first }}"

- name: Printing the json
  debug:
    var: "json"

# - name: Setting up the configuration for the iSCSI service
#   include_tasks: "{{ role_common_task_web_put }}"
#   vars:
#     url: "{{ api_url }}/iscsi/global"
#     body: "{{ lookup('template', 'iscsi/config-global.json') }}"

# - name: Setting up the configuration for the iSCSI service
#   include_tasks: "{{ role_common_task_web_post }}"
#   vars:
#     url: "{{ api_url }}/iscsi/portal"
#     body: "{{ lookup('template', 'iscsi/config-portal.json') }}"

# - name: Setting up the configuration for the iSCSI service
#   include_tasks: "{{ role_common_task_web_post }}"
#   vars:
#     url: "{{ api_url }}/iscsi/initiator"
#     body: "{{ lookup('template', 'iscsi/config-initiator.json') }}"

# - name: Setting up the configuration for the iSCSI service
#   include_tasks: "{{ role_common_task_web_post }}"
#   vars:
#     url: "{{ api_url }}/iscsi/auth"
#     body: "{{ lookup('template', 'iscsi/config-auth.json') }}"

# - name: Setting up the configuration for the iSCSI service
#   include_tasks: "{{ role_common_task_web_post }}"
#   vars:
#     url: "{{ api_url }}/iscsi/target"
#     body: "{{ lookup('template', 'iscsi/config-target.json') }}"

- name: Enabling the iSCSI service to start on boot
  include_tasks: "{{ role_common_task_web_put }}"
  vars:
    url: "{{ api_url }}/service/id/{{ json.id }}"
    body: "{{ lookup('template', 'service/enable.json') }}"

- name: Starting the iSCSI service
  include_tasks: "{{ role_common_task_web_post }}"
  vars:
    url: "{{ api_url }}/service/start"
    service: "{{ json.service }}"
    body: "{{ lookup('template', 'service/start.json') }}"
