---
- name: Including the file that contains specific settings
  include_vars: "host_vars/{{ host }}.yml"

- name: Setting up the SSH service
  import_tasks: "ssh/main.yml"

- name: Setting up the S.M.A.R.T. service
  import_tasks: "smart/main.yml"

- name: Setting up the NFS service
  import_tasks: "nfs/main.yml"

- name: Setting up the iSCSI service
  import_tasks: "iscsi/main.yml"
