---
# - name: Setting up the SSH service
#   import_tasks: "01-ssh.yml"

# - name: Setting up the S.M.A.R.T. service
#   import_tasks: "02-smartd.yml"

- name: Setting up the iSCSI service
  import_tasks: "03-iscsitarget.yml"
