---
- name: Including the file that contains specific settings
  include_vars: "{{ item }}.yml"

- name: Getting the list of services 
  include_tasks: "{{ role_common_task_web_get }}"
  vars:
    url: "{{ api_url }}/service"

- name: Getting the current settings of the {{ service.display_name }} service
  set_fact:
    json: "{{ response.json | json_query(querystr) | first }}"
  vars:
    querystr: "[?service=='{{ service.name }}']"

- name: Printing the json
  debug:
    var: "json"

- name: Setting up the configuration for the {{ service.display_name }} service
  include_tasks: "{{ service.name }}/config.yml"

- name: Enabling the {{ service.display_name }} service to start on boot
  include_tasks: "{{ role_common_task_web_put }}"
  vars:
    url: "{{ api_url }}/service/id/{{ json.id }}"
    body: "{{ lookup('template', 'service/enable.json') }}"

- name: Starting the {{ service.display_name }} service
  include_tasks: "{{ role_common_task_web_post }}"
  vars:
    url: "{{ api_url }}/service/start"
    service: "{{ json.service }}"
    body: "{{ lookup('template', 'service/start.json') }}"
