---
- name: Including the file that contains specific settings
  include_vars: "host_vars/{{ host }}.yml"

- name: Getting the list of services 
  include_tasks: "{{ role_common_task_uri_service_get }}"

- name: Getting the current settings of the {{ item.display_name }} service
  set_fact:
    json: "{{ response.json | json_query(querystr) | first }}"
  vars:
    querystr: "[?service=='{{ item.name }}']"

- name: Including the task that will setup the service with the desired values
  include_tasks: "{{ item.name }}/config.yml"

- name: Enabling the {{ item.display_name }} service to start on boot
  include_tasks: "{{ role_common_task_uri_service_enable }}"
  vars:
    service_id: "{{ json.id }}"
  when: json.enable != true

- name: Starting the {{ item.display_name }} service
  include_tasks: "{{ role_common_task_uri_service_start }}"
  vars:
    service: "{{ json.service }}"
  when: json.state != "RUNNING"
