---
# - name: Reading the json file that contains the desired settings
#   include_tasks: "get-desired-settings.yml"

# - name: Getting the current mail settings
#   include_tasks: "get-current-settings.yml"

# - name: Comparing the desired and current settings
#   include_tasks: "{{ role_common_task_shared_compare_dict_json }}"
  # vars:
  #     dict: "{{ desired_settings }}"
  #     json: "{{ response.json }}"

# - name: Setting the mail settings
#   include_tasks: "update.yml"
#   when: different_settings | length > 0
